name: First Workflow
# workflow_dispatch is used to manually trigger workflow
# Workflow triggers (also called events) can be found here: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
on: workflow_dispatch
jobs:
  # first-JOB is a name we can give freely
  first-JOB:
    # Possible runners can be found here: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    # Defines the environment that we run the workflow on
    runs-on: ubuntu-latest
    steps:
      #List of steps. Each step starts with a dash
      - name: Print Greeting
        run: echo "Hello world"
      - name: Print Goodbye
        run: echo "BYEEE"
      - name: Run 2 lines
        run: |
          echo "line 1"
          echo "line 2"
        
